### PR TITLE
Add pytest.ini to ensure all tests get run

### PR DESCRIPTION
**Pull request by Bjwebb**

### CODE REVIEW

**Comment by odscjames** [comment]
https://travis-ci.com/open-contracting/cove-ocds/builds/147748360#L573 

Have you seen this before @Bjwebb @rhiaro ?

```
E       AssertionError: assert 'fetching failed' == '404: not found'
E         - fetching failed
E         + 404: not found
```

**Comment by Bjwebb** [comment]
I saw it today on the main cove repo, so I think its something about a remote resource that has changed.

**Comment by odscjames** [comment]
[Refactor OCDS-specific code into a new application](https://trello.com/c/6SyOfmT6/49-refactor-ocds-specific-code-into-a-new-application)

**Comment by Bjwebb** [comment]
I've reviewed @odscjames's changes to this, and they look good. (Can't leave an actual review as its my PR).

**Pull request merged**
