### PR TITLE
sass: Make the headlines box red when validation fails

### PR DESCRIPTION
**Pull request by Bjwebb**
Also, change the color of all danger boxes to a darker red.

https://github.com/OpenDataServices/cove/issues/845

* Update build_ocds.sh to not use deprecated command or options.
* Add libsass to requirements_dev.in, and compile requirements files
* Update _bootstrap-variables-ocds.sass with some colour changes
* Rerun ./build_ocds.sh
* Update headline box template to use panel-danger when structural validation or extensions fail
* Add some docs of making sass changes

Dev deploy: http://cove.dev1.cove.opencontracting.uk0.bigv.io/review/

### CODE REVIEW

**Comment by Bjwebb** [comment]
@jpmckinney I think it would be useful to have a dev deploy of this for people to test. There's no cove-ocds dev server at the moment. Would it be appropriate to create a new server in the opencontracting Bytemark for this?

**Comment by jpmckinney** [comment]
@Bjwebb Sure, we can spin up a server. Is it something that needs to run continuously, or is it easy enough to create a server when needed?

**Comment by Bjwebb** [comment]
@jpmckinney I think we're somewhere in the middle at the moment. Once we can run salt, its just a matter of a single command, but there's a few manual [steps before that](https://ocdsdeploy.readthedocs.io/en/latest/deploy/create_server.html).

So, I think the easiest thing to do now, is to have a box with the lowest spec running continuously. However, we might want to get into the practice of deploying from scratch, and maybe automate more of those steps (as mentioned in https://github.com/open-contracting/deploy/issues/156).

**Comment by jpmckinney** [comment]
Sounds good. Feel free to create a new server on Bytemark in an appropriate group. While doing that, feel free to update https://github.com/open-contracting/deploy/issues/115 with a proposed naming scheme for targets.

**Comment by Bjwebb** [comment]
@jpmckinney I've just logged to the LastPass, to add the server password. I think you'll get an email about it.

**Comment by jpmckinney** [comment]
@Bjwebb Thanks, I've verified your device, so you should be able to login now.

**Comment by Bjwebb** [comment]
New server at dev1.cove.opencontracting.uk0.bigv.io. Cove url is http://cove.dev1.cove.opencontracting.uk0.bigv.io/review/
I've added the password to LastPass. 

For [Update external services](https://ocdsdeploy.readthedocs.io/en/latest/deploy/create_server.html#update-external-services):
* I've set up Prometheus.
* There's no DNS, or additional managed passwords.
* Its not added to Health spreadsheet or UptimeRobot yet.
* It uses the same Sentry and Google Analytics as the live deploy.

**Comment by jpmckinney** [comment]
Health spreadsheet is just for production services – same for UptimeRobot, so I think okay not to do those.

**Pull request merged**
