### PR TITLE
[WIP] Docs init

### PR DESCRIPTION
**Pull request by jpmckinney**
Outline, stubs, and some content for docs for cove-ocds and lib-cove-ocds.

### CODE REVIEW

**Comment by jpmckinney** [comment]
[Write overview documentation for the DRT](https://trello.com/c/Y07UW30f/15-write-overview-documentation-for-the-drt)

**Comment by jpmckinney** [comment]
@rhiaro I had to re-create the PR, because apparently deleting the `1-drt` branch (after making it `master`) auto-closed the other PR, with no option to edit the branch to merge into.

**Comment by odscjames** [comment]
* in the index python `manage.py runserver 0.0.0.0:8000` - the IP/port bit is only required if running in a virtual thing (Vagrant, docker, etc). This can technically open up a security thing where other people on the same network as you can interact with your dev server - that's the reason binding to 127.0.0.1 is the default. But that's really minor.
* sphinx / sphinx-rtd-theme are duplicated in the req_dev.in file. But they are only once in the txt file, so pip-tools has fixed that for us.


The rest looks like a great start to me, and the above looks minor - I'm going to approve, and I would suggest merging in sooner rather than later and then the authors can continue docs writing in another branch. This will allow us to start setting up RTD, if that hasn't been done already. Also this branch includes the conversion to piptools, and we want that in master soon otherwise there will be conflicts.

I'm just going to hold off pushing the actual button because the title says "WIP" and I'm not sure why. So I will pass back to @rhiaro or @jpmckinney

**Comment by odscjames** [comment]
Another small thing taken from #11 by @Bjwebb - Use `python3 -m venv .ve` instead of `virtualenv .ve --python=/usr/bin/python3` as depending on how people install things, that will work for more people. This also raises the note that after this one is merged in, the next branch could cut down the readme to avoid duplication.

**Comment by jpmckinney** [comment]
No need for me to review – I only happen to be the PR author because switching the master branch closed the original PR.

**Pull request merged**
