### PR TITLE
Add HotJar

### PR DESCRIPTION
**Pull request by odscjames**

### CODE REVIEW

**Comment by odscjames** [comment]
[Set up Hotjar](https://trello.com/c/KLHW48Fc/18-set-up-hotjar)

**Comment by odscjames** [comment]
> <p>{% blocktrans %} .... For more information and to learn how to opt out of this, see the {% endblocktrans %}<a href="{% url 'terms' %}#privacy_notice">{% trans "Privacy Notice" %}</a>.</p>

I want to look up what the expert advice is for how you get A tags to work with trans blocks nicely - I'm not totally sure this is the best for translators

**Comment by jpmckinney** [comment]
Per https://docs.djangoproject.com/en/3.0/topics/i18n/translation/#blocktrans-template-tag, you typically do:

```
{% url 'terms' as terms_url %}
{% blocktrans %}
We also collect server logs, which we analyse from time to time to understand traffic to the site. Users cannot opt out of this data collection, and data is treated with respect. For more information, see the <a href="{{ terms_url }}#privacy_notice">Privacy Notice</a>.
{% endblocktrans %}

**Comment by odscjames** [comment]
Thanks.

Once https://github.com/OpenDataServices/lib-cove-web/pull/37 is merged this just needs some light editing and it's ready for the translators.

**Comment by odscjames** [comment]
This is now ready to go to the translators

**Comment by odscjames** [comment]
Ready :-)

**Comment by jpmckinney** [comment]
Great! I don't know if I shared previously, but the snippet is:

```html
<!-- Hotjar Tracking Code for https://standard.open-contracting.org/review/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1501232,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
```

i.e. for the environment variables:

ID: 1501232
SV: 6

**Pull request merged**
