### PR TITLE
libcoveocds already offers a CLI

### PR DESCRIPTION
**Pull request by jpmckinney**
Follow-up to https://github.com/open-contracting/cove-oc4ids/issues/55

### CODE REVIEW

**Comment by Bjwebb** [comment]
It looks to me like this cove-ocds CLI code has more options and more tests than the lib-cove-ocds CLI code, so we should move those over before merging this.

**Comment by Bjwebb** [comment]
[Remove CLI from cove-ocds](https://trello.com/c/LYQf25pV/88-remove-cli-from-cove-ocds)

**Comment by odscjames** [comment]
In https://github.com/open-contracting/lib-cove-ocds/pull/55 options were added to that libraries CLI.

**Comment by jpmckinney** [comment]
Merging since options were added per above.

**Pull request merged**
